import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-zinc-950 dark:bg-white`}>
        <main className='mx-auto min-h-screen max-w-7xl text-slate-100'>
          <Navbar />
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
